### ISSUE TITLE
DUI Squad Radar shows up in S.O.G. Prairie Fire Main Menu

### ISSUE THREAD

**Issue by y0014984** [diwako/diwako_dui#197] opened 2021-06-15 13:53 UTC
**Mods:**

- **Arma 3:** `2.04.147757 profiling`
- **S.O.G. Prairie Fire:** `1.01.006333`
- **CBA:** `3.15.3.210310 stable`
- **DUI:** `1.9.2 stable`

**Description:**

If Arma 3 is started with the new Creator DLC S.O.G. Prairie Fire, the game shows a custom main menu. In that main menu, the DUI Squad Radar is visible. The radar is only visible if the game is not startet with the parameter -skipIntro and -world=empty and has loaded a world in the main menu background. 

**Steps to reproduce:**

- Start the game with listed DLCs and Mods, but without startup parameter -skipIntro and -world=empty

**Expected behavior:**

Squad Radar should not be visible in main menu.

**Where did the issue occur?**

- S.O.G. PRairie Fire Main Menu

**Additional context:**

DUI Squad Radar is only shown without the startup parameter -skipIntro and -world=empty

**Log Files:**

- https://pastebin.com/Qe9cPWne

**Screenshots:**

https://imgur.com/a/LF3qytH

**Comment by jokoho48** [comment] 2021-06-15 22:38
This is caused by SOG Cameras not being registered in the CBA Feature Camera System fixed with https://github.com/CBATeam/CBA_A3/pull/1466. Not a DUI so I am going to close this Issue.

**Closed by jokoho48** 2021-06-15 22:38 UTC
Labels: bug

**Comment by diwako** [comment] 2021-06-17 16:24
Fix is now merged in cba
https://github.com/CBATeam/CBA_A3/pull/1466
