### ISSUE TITLE
Bug - Compass UI became stretched during gameplay.

### ISSUE THREAD

**Issue by josh-000** [diwako/diwako_dui#8] opened 2019-01-19 20:55 UTC
During an OP with UAG. The compass image/UI became stretched and warped. I havent got an image right now but I'll update with one.

**Comment by josh-000** [comment] 2019-01-19 20:57
![image](https://user-images.githubusercontent.com/36608870/51432282-e05f6e00-1c2c-11e9-865d-9f1011581c46.png)

**Comment by josh-000** [comment] 2019-01-19 21:39
https://www.youtube.com/watch?v=lBJ3P1DfxQU&feature=youtu.be

Here is a video of the bug. I am running the game in fullscreen in 1920x1080.

**Comment by diwako** [comment] 2019-01-19 21:51
Need a bit more information. 
Sampling rate and anything under "Display"

**Comment by diwako** [comment] 2019-01-22 08:01
While I could not recreate the issue. I added a feature which will make the compass and namelist rerender if you hide the UI with the keybind and show it again.

However, not sure if this will fix the issue or not.

**Comment by diwako** [comment] 2019-01-29 13:02
Similar bug, but not the same.
Compass Control becomes squished if you look around, but is fine when looking north

https://www.youtube.com/watch?v=OQSQbRUymU4

**Comment by Cyruz143** [comment] 2019-01-29 13:07
@diwako that video looks like a non-standard FOV, might be the cause.

**Comment by diwako** [comment] 2019-01-29 13:39
Confirmed, custom FOV

fovTop=1.36;
fovLeft=2.4100001;

**Comment by diwako** [comment] 2019-01-31 20:10
Bug was reproducable. You had to launch the game in windowed mode (borderless does work as well) and resize the window. 
For borderless it can happen while alt tabbing.

The fix for this was indeed the button combination to toggle hud on and off. It only has to be done when the alt-tabbing or resizing the window, so I consider the button binding a fix without constantly setting the compasses size.

**Closed by diwako** 2019-01-31 20:10 UTC
Labels: bug, needs more info
