### ISSUE TITLE
Bug - Namelist in wrong order for JIP

### ISSUE THREAD

**Issue by McDiod** [diwako/diwako_dui#82] opened 2019-04-08 21:12 UTC
The order in which the namelist is sorted for JIP players can apparently differ from how the rest of the group sees it.

**Comment by AdlerXiviD** [comment] 2019-04-08 21:19
Can confirm.

**Comment by diwako** [comment] 2019-04-09 06:05
Hm, first I heard of this.

@McDiod @AdlerXiviD Any specific way to replicate this?

**Comment by McDiod** [comment] 2019-04-09 08:12
We haven't tried yet. The way this happened yesterday was:

1. group of four players, mission starts
2. one player disconnects
3. FTL assigns buddy teams
4. disconnected player reconnects on the same slot
5. reconnected player sees namelist in a different order

We are using BI`s dynamic group system. The groups callsign is set during postInit by a third script. Either that has something to do with it, or the `units group` array is unreliable during postInit? Maybe some units are still null during initialization, so your cache loop skips them first, then adds them later resulting in a different order.

**Comment by diwako** [comment] 2019-04-09 08:31
The cache loop grabs the units using `units group _player` meaning it is using the what ever the game gives back.

What would be interesting would be in which order these are returned and what internal names these units get assigned on each machine.

E.g.
Bravo 1-3:1 or the like or by assigning an empty string as `vehicleName`

Meaning it might be possible to sort by the internal name to sync things for everyone.

Here a small script for the debug console to get the current squad members internal names, (be aware this will remove any sort of display variable name given to them)
```sqf
private _grp = units group ace_player;
{
  _x setVehicleVarName "";
} forEach _grp;

_grp
```

**Comment by diwako** [comment] 2019-04-09 08:51
I am not too familiar with gruppe Adlers mods (besides trenches), would help if you could link me their GitHub repo for this (if it is openly available)
@McDiod

**Comment by Fusselwurm** [comment] 2019-04-09 09:58
https://github.com/gruppe-adler/gruppe_adler_mod ; groups-related code is in https://github.com/gruppe-adler/gruppe_adler_mod/tree/master/addons/dynGroups

**Comment by McDiod** [comment] 2019-04-09 11:03
The gruppe adler mod component just modifies BI's dynamic group system slightly, shouldn't be relevant here.

The mission template that was used can be found here:

https://github.com/gruppe-adler/CO_Template.VR

See my last reply for the relevant code (\functions\groupsettings).

**Comment by diwako** [comment] 2019-04-09 11:09
Since this is the first report with name list being out of order, I assume it has something to do with BIS dynamic groups. I personally do not use it, nor do the groups I play in. So it never really came up.

So, I'd need some help reproducing the bug and debugging it. Maybe the bug comes up even without the Dynamic Group feature, not sure. It take multiple people to debug this sadly.

**Comment by diwako** [comment] 2019-04-10 19:37
Testing was done, findings were as follows

Replication
1. have two groups
2. someone disconnects from group A
3. Someone from group B joins the group
4. someone reconnects into group A

Resulting asynchronicity.
```
diwako's machine:
[B Alpha 1-2:1 (Diwako),B Alpha 1-2:2 (nomisum) REMOTE,B Alpha 1-2:3 (Salbei250) REMOTE,B Alpha 1-2:4 (McDiod) REMOTE]
McDiod's machine:
[B Alpha 1-2:1 (nomisum) REMOTE,B Alpha 1-2:2 (Diwako) REMOTE,B Alpha 1-2:3 (Salbei250) REMOTE,B Alpha 1-2:4 (McDiod)]
```

That basically means, it is NOT possible to sort them according to their internal squad names, as these are already out of sync.

This seems to be a BI bug. It could be ""fixed"" by recreating the group and giving its all the same values or by using one unit in the squad to share their order.
However that would mean DUI would not be a client side only addon anymore.

**Comment by diwako** [comment] 2019-04-17 11:49
PR was merged, preview is already on the dev workshop item. Closing this now, if you find anything lacking feel free to notify me

**Closed by diwako** 2019-04-17 11:49 UTC
Labels: BI Fault, help wanted
