### ISSUE TITLE
Bug - Script error when using ACRE Godmode

### ISSUE THREAD

**Issue by Theowningone** [diwako/diwako_dui#145] opened 2020-09-19 02:01 UTC
The [new](https://github.com/IDI-Systems/acre2/releases/tag/v2.8.0.1037) ACRE release comes with a "Godmode" feature. DUI throws a script error when using it.

[Some of the ACRE documentation on godmode](https://acre2.idi-systems.com/wiki/frameworks/god-mode) (not sure how helpful it will be)

The script error:
```
21:55:08 Error in expression <io", false]];

_onRadio = [false, true] select _onRadio;
if (diwako_dui_radar_sh>
21:55:08   Error position: <select _onRadio;
if (diwako_dui_radar_sh>
21:55:08   Error Zero divisor
21:55:08 File z\diwako_dui\addons\radar\XEH_preInit.sqf..., line 635
```

**Comment by diwako** [comment] 2020-09-19 21:12
Thanks for the report. The issue happened before due to radio racks, however very sporadically, so we could never pin it down.

Is it possible to reproduce the issue with the god mode feature reliably?

**Comment by diwako** [comment] 2020-09-21 17:21
Issue was found, will be fixed in next update!

**Comment by diwako** [comment] 2020-10-01 07:39
Fix is now available on DEV workshop item!
https://steamcommunity.com/sharedfiles/filedetails/?id=1617125729

**Closed by diwako** 2020-10-01 07:39 UTC
